// 中國歷代帝王資料（周、秦、漢）— 僅收錄至 AD 421
// row: 2，配合 ZH_ROW_LABELS 第三欄「帝王」

const ZH_EMPERORS = [

  // ══ 西周（-1046 ~ -771）══════════════════════════════════════════
  { name:'武王', en:'King Wu of Zhou – defeated Shang, founded Zhou dynasty',
    start:-1046, end:-1043, color:'#d97706', row:2, personal:'姬發', wikiEn:'King_Wu_of_Zhou' },
  { name:'成王', en:'King Cheng of Zhou – Duke of Zhou served as regent',
    start:-1042, end:-1021, color:'#f59e0b', row:2, personal:'姬誦', wikiEn:'King_Cheng_of_Zhou' },
  { name:'康王', en:'King Kang of Zhou – peaceful golden age of early Zhou',
    start:-1020, end:-996,  color:'#fbbf24', row:2, personal:'姬釗', wikiEn:'King_Kang_of_Zhou' },
  { name:'昭王', en:'King Zhao of Zhou – died on southern campaign',
    start:-995,  end:-977,  color:'#fde68a', row:2, personal:'姬瑕', wikiEn:'King_Zhao_of_Zhou' },
  { name:'穆王', en:'King Mu of Zhou – legendary traveller, met Queen Mother of the West',
    start:-976,  end:-922,  color:'#d97706', row:2, personal:'姬滿', wikiEn:'King_Mu_of_Zhou' },
  { name:'共王', en:'King Gong of Zhou',
    start:-922,  end:-900,  color:'#f59e0b', row:2, personal:'姬繄扈' },
  { name:'懿王', en:'King Yi of Zhou',
    start:-899,  end:-892,  color:'#fbbf24', row:2, personal:'姬囏' },
  { name:'孝王', en:'King Xiao of Zhou',
    start:-891,  end:-886,  color:'#fde68a', row:2, personal:'姬辟方', wikiEn:'King_Xiao_of_Zhou' },
  { name:'夷王', en:'King Yi II of Zhou',
    start:-885,  end:-878,  color:'#d97706', row:2, personal:'姬燮' },
  { name:'厲王', en:'King Li of Zhou – tyrannical rule, exiled by nobles in 841 BC',
    start:-877,  end:-841,  color:'#f59e0b', row:2, personal:'姬胡', wikiEn:'King_Li_of_Zhou' },
  // -841 ~ -827 共和行政（無君）
  { name:'宣王', en:'King Xuan of Zhou – Zhou revival, first year of verified Chinese chronology',
    start:-827,  end:-782,  color:'#fbbf24', row:2, personal:'姬靜', wikiEn:'King_Xuan_of_Zhou' },
  { name:'幽王', en:'King You of Zhou – lit beacon fires for concubine Bao Si; Western Zhou ended',
    start:-781,  end:-771,  color:'#fde68a', row:2, personal:'姬宮湦', wikiEn:'King_You_of_Zhou' },

  // ══ 東周（-770 ~ -256）══════════════════════════════════════════
  { name:'平王', en:'King Ping of Zhou – moved capital east to Luoyi, began Eastern Zhou',
    start:-770,  end:-720,  color:'#78350f', row:2, personal:'姬宜臼', wikiEn:'King_Ping_of_Zhou' },
  { name:'桓王', en:'King Huan of Zhou – defeated by Zheng at Battle of Xuge',
    start:-719,  end:-697,  color:'#92400e', row:2, personal:'姬林', wikiEn:'King_Huan_of_Zhou' },
  { name:'莊王', en:'King Zhuang of Zhou',
    start:-696,  end:-682,  color:'#b45309', row:2, personal:'姬佗' },
  { name:'釐王', en:'King Xi of Zhou',
    start:-681,  end:-677,  color:'#d97706', row:2, personal:'姬胡齊' },
  { name:'惠王', en:'King Hui of Zhou',
    start:-676,  end:-652,  color:'#78350f', row:2, personal:'姬閬' },
  { name:'襄王', en:'King Xiang of Zhou – era of Duke Huan of Qi as hegemon',
    start:-651,  end:-619,  color:'#92400e', row:2, personal:'姬鄭' },
  { name:'頃王', en:'King Qing of Zhou',
    start:-618,  end:-613,  color:'#b45309', row:2, personal:'姬壬臣' },
  { name:'匡王', en:'King Kuang of Zhou',
    start:-612,  end:-607,  color:'#d97706', row:2, personal:'姬班' },
  { name:'定王', en:'King Ding of Zhou – Chu asked about Zhou\'s bronze ritual vessels',
    start:-606,  end:-586,  color:'#78350f', row:2, personal:'姬瑜' },
  { name:'簡王', en:'King Jian of Zhou',
    start:-585,  end:-572,  color:'#92400e', row:2, personal:'姬夷' },
  { name:'靈王', en:'King Ling of Zhou',
    start:-571,  end:-545,  color:'#b45309', row:2, personal:'姬泄心' },
  { name:'景王', en:'King Jing of Zhou – cast large bells, succession dispute after death',
    start:-544,  end:-520,  color:'#d97706', row:2, personal:'姬貴' },
  { name:'悼王', en:'King Dao of Zhou – short reign amid civil war',
    start:-520,  end:-519,  color:'#78350f', row:2, personal:'姬猛' },
  { name:'敬王', en:'King Jing II of Zhou – Zhou authority further diminished',
    start:-519,  end:-476,  color:'#92400e', row:2, personal:'姬丐' },
  { name:'元王', en:'King Yuan of Zhou',
    start:-475,  end:-469,  color:'#b45309', row:2, personal:'姬仁' },
  { name:'貞定王', en:'King Zhending of Zhou',
    start:-468,  end:-441,  color:'#d97706', row:2, personal:'姬介' },
  { name:'哀王', en:'King Ai of Zhou – killed by brother after months',
    start:-441,  end:-440,  color:'#78350f', row:2, personal:'姬去疾' },
  { name:'思王', en:'King Si of Zhou – killed by brother after months',
    start:-440,  end:-439,  color:'#92400e', row:2, personal:'姬叔' },
  { name:'考王', en:'King Kao of Zhou',
    start:-439,  end:-426,  color:'#b45309', row:2, personal:'姬嵬' },
  { name:'威烈王', en:'King Weilie of Zhou – recognized Han, Wei, Zhao as lords',
    start:-425,  end:-402,  color:'#d97706', row:2, personal:'姬午' },
  { name:'安王', en:'King An of Zhou',
    start:-401,  end:-376,  color:'#78350f', row:2, personal:'姬驕' },
  { name:'烈王', en:'King Lie of Zhou',
    start:-375,  end:-369,  color:'#92400e', row:2, personal:'姬喜' },
  { name:'顯王', en:'King Xian of Zhou – long reign, Zhou a mere formality',
    start:-368,  end:-321,  color:'#b45309', row:2, personal:'姬扁' },
  { name:'慎靚王', en:'King Shenjing of Zhou',
    start:-320,  end:-315,  color:'#d97706', row:2, personal:'姬定' },
  { name:'赧王', en:'King Nan of Zhou – last Zhou king, died as Qin took Luoyi',
    start:-314,  end:-256,  color:'#78350f', row:2, personal:'姬延', wikiEn:'King_Nan_of_Zhou' },

  // ══ 秦（-221 ~ -206）══════════════════════════════════════════════
  { name:'始皇帝', en:'Qin Shi Huang – First Emperor of China',
    start:-221, end:-210, color:'#6b7280', row:2, personal:'嬴政', wikiEn:'Qin_Shi_Huang' },
  { name:'秦二世', en:'Qin Er Shi',
    start:-210, end:-207, color:'#9ca3af', row:2, personal:'胡亥', wikiEn:'Qin_Er_Shi' },
  { name:'子嬰',   en:'Ziying – last ruler of Qin',
    start:-207, end:-206, color:'#d1d5db', row:2, personal:'子嬰' },

  // ══ 西漢（-206 ~ 9）══════════════════════════════════════════════
  { name:'高帝', en:'Emperor Gaozu of Han',
    start:-206, end:-195, color:'#dc2626', row:2, nianHao:'（無）', personal:'劉邦', wikiEn:'Emperor_Gaozu_of_Han' },
  { name:'惠帝', en:'Emperor Hui of Han',
    start:-195, end:-188, color:'#ef4444', row:2, nianHao:'（無）', personal:'劉盈', wikiEn:'Emperor_Hui_of_Han' },
  { name:'文帝', en:'Emperor Wen of Han',
    start:-180, end:-157, color:'#f87171', row:2, nianHao:'（無）', personal:'劉恆', wikiEn:'Emperor_Wen_of_Han' },
  { name:'景帝', en:'Emperor Jing of Han',
    start:-157, end:-141, color:'#fca5a5', row:2, nianHao:'（無）', personal:'劉啟', wikiEn:'Emperor_Jing_of_Han' },
  { name:'武帝', en:'Emperor Wu of Han – first to use era names',
    start:-141, end:-87,  color:'#dc2626', row:2, nianHao:'建元', personal:'劉徹', wikiEn:'Emperor_Wu_of_Han' },
  { name:'昭帝', en:'Emperor Zhao of Han',
    start:-87,  end:-74,  color:'#ef4444', row:2, nianHao:'始元', personal:'劉弗陵', wikiEn:'Emperor_Zhao_of_Han' },
  { name:'宣帝', en:'Emperor Xuan of Han',
    start:-74,  end:-49,  color:'#f87171', row:2, nianHao:'本始', personal:'劉詢', wikiEn:'Emperor_Xuan_of_Han' },
  { name:'元帝', en:'Emperor Yuan of Han',
    start:-49,  end:-33,  color:'#fca5a5', row:2, nianHao:'初元', personal:'劉奭', wikiEn:'Emperor_Yuan_of_Han' },
  { name:'成帝', en:'Emperor Cheng of Han',
    start:-33,  end:-7,   color:'#dc2626', row:2, nianHao:'建始', personal:'劉驁', wikiEn:'Emperor_Cheng_of_Han' },
  { name:'哀帝', en:'Emperor Ai of Han',
    start:-7,   end:-1,   color:'#ef4444', row:2, nianHao:'建平', personal:'劉欣', wikiEn:'Emperor_Ai_of_Han' },
  { name:'平帝', en:'Emperor Ping of Han',
    start:-1,   end:6,    color:'#f87171', row:2, nianHao:'元始', personal:'劉衎', wikiEn:'Emperor_Ping_of_Han' },
  { name:'孺子嬰', en:'Ruzi Ying',
    start:6,    end:9,    color:'#fca5a5', row:2, personal:'劉嬰' },

  // ══ 東漢（25 ~ 220）══════════════════════════════════════════════
  { name:'光武帝', en:'Emperor Guangwu – founder of Eastern Han',
    start:25,   end:57,   color:'#c2410c', row:2, nianHao:'建武', personal:'劉秀', wikiEn:'Emperor_Guangwu_of_Han' },
  { name:'明帝', en:'Emperor Ming of Han',
    start:57,   end:75,   color:'#ea580c', row:2, nianHao:'永平', personal:'劉莊', wikiEn:'Emperor_Ming_of_Han' },
  { name:'章帝', en:'Emperor Zhang of Han',
    start:75,   end:88,   color:'#f97316', row:2, nianHao:'建初', personal:'劉炟', wikiEn:'Emperor_Zhang_of_Han' },
  { name:'和帝', en:'Emperor He of Han',
    start:88,   end:106,  color:'#fb923c', row:2, nianHao:'永元', personal:'劉肇', wikiEn:'Emperor_He_of_Han' },
  { name:'安帝', en:'Emperor An of Han',
    start:106,  end:125,  color:'#c2410c', row:2, nianHao:'永初', personal:'劉祜', wikiEn:'Emperor_An_of_Han' },
  { name:'順帝', en:'Emperor Shun of Han',
    start:125,  end:144,  color:'#ea580c', row:2, nianHao:'永建', personal:'劉保', wikiEn:'Emperor_Shun_of_Han' },
  { name:'沖帝', en:'Emperor Chong of Han',
    start:144,  end:145,  color:'#f97316', row:2, nianHao:'永嘉', personal:'劉炳' },
  { name:'質帝', en:'Emperor Zhi of Han',
    start:145,  end:146,  color:'#fb923c', row:2, nianHao:'本初', personal:'劉纘' },
  { name:'桓帝', en:'Emperor Huan of Han',
    start:146,  end:168,  color:'#c2410c', row:2, nianHao:'建和', personal:'劉志', wikiEn:'Emperor_Huan_of_Han' },
  { name:'靈帝', en:'Emperor Ling of Han',
    start:168,  end:189,  color:'#ea580c', row:2, nianHao:'建寧', personal:'劉宏', wikiEn:'Emperor_Ling_of_Han' },
  { name:'獻帝', en:'Emperor Xian of Han – last Han emperor',
    start:189,  end:220,  color:'#f97316', row:2, nianHao:'初平', personal:'劉協', wikiEn:'Emperor_Xian_of_Han' },

];
