// 中國歷史：重大事件
const ZH_EVENTS = [
  // ── 夏商 ────────────────────────────────────────────────────────────────────
  { year: -2070, text: '夏朝建立（傳說時代）', textEn: 'Xia Dynasty founded (legendary era)' },
  { year: -1600, text: '商湯滅夏，商朝建立', textEn: 'Shang Tang overthrows Xia; Shang Dynasty founded' },
  { year: -1300, text: '商王盤庚遷都至殷（今河南安陽），殷墟甲骨文繁盛——現存最早成熟文字系統', textEn: 'King Pangeng moves capital to Yin (Anyang); oracle bone script flourishes — earliest mature writing system' },
  { year: -1046, text: '牧野之戰：武王伐紂，商朝覆滅，周朝建立；姜太公輔佐，大軍臨陣商人倒戈', textEn: 'Battle of Muye: King Wu overthrows Shang tyrant Zhouxin; Zhou Dynasty founded with Jiang Taigong\'s aid' },

  // ── 西周（-1046 ~ -771）───────────────────────────────────────────────────
  { year: -1042, text: '周公旦攝政：武王崩後，周公以攝政王身份輔佐成王；「三監之亂」（管叔、蔡叔聯合商遺族武庚叛亂），周公東征三年平叛', textEn: 'Duke of Zhou regents for King Cheng; suppresses Three Guards Rebellion with three-year eastern campaign' },
  { year: -1036, text: '周公制禮作樂：建立宗法封建制度、五禮體系與雅樂規範，奠定「周禮」——中國文化三千年的制度基礎', textEn: 'Duke of Zhou codifies Zhou Rites — ceremonial and feudal foundations of Chinese civilization for 3,000 years' },
  { year: -1020, text: '成王親政，大規模分封諸侯：魯（周公後裔）、齊（姜太公後裔）、燕、晉等八百諸侯確立，西周封建體制完成', textEn: 'King Cheng rules directly; eight hundred feudal states established (Lu, Qi, Yan, Jin); Western Zhou feudal system complete' },
  { year: -977,  text: '周昭王南征荊楚，渡漢水時溺斃，全軍覆沒；此為周王室衰弱的第一個信號，後世諱莫如深不敢追究', textEn: 'King Zhao of Zhou drowns crossing Han River on southern campaign — first sign of Zhou royal decline' },
  { year: -841,  text: '周厲王暴政，「防民之口甚於防川」；國人暴動，厲王出奔于彘；周召二公共行攝政（共和行政）——西元前 841 年是中國歷史確切紀年的起點', textEn: 'King Li of Zhou tyrannizes; people revolt, king flees; Regency of Gong He (841 BC) — China\'s earliest confirmed historical year' },
  { year: -827,  text: '宣王中興：周宣王即位，北伐玁狁、東征淮夷、南征荊楚，一時王室復振；但晚年千畝之戰敗於姜戎，中興成果動搖', textEn: 'King Xuan restoration: campaigns north and south revive Zhou prestige; later defeated at Qianmu by Jiang Rong' },
  { year: -771,  text: '「烽火戲諸侯」傳說：幽王廢申后立褒姒，申侯引犬戎入侵；幽王死於驪山下，西周覆滅；平王東遷洛邑，東周（春秋時代）開始', textEn: 'Dog Rong invades; King You of Zhou killed; Western Zhou falls; King Ping moves east to Luoyi — Eastern Zhou (Spring and Autumn) begins' },

  // ── 春秋（-770 ~ -476）──────────────────────────────────────────────────
  { year: -770,  text: '秦襄公護送周平王東遷立功，正式獲封諸侯——秦國從周王室邊陲馬夫領地升格為合法諸侯國，關中之地由此奠定', textEn: 'Qin Xianggong escorts King Ping east; Qin officially elevated to feudal state — foundation of Qin\'s rise' },
  { year: -704,  text: '楚武王熊通自稱「王」：「我蠻夷也，不與中國之號諡」——周天子分封體制被徹底挑戰，此後吳、越相繼稱王，春秋禮樂秩序名存實亡', textEn: 'King Wu of Chu declares himself king, defying Zhou — Zhou feudal hierarchy permanently challenged' },
  { year: -707,  text: '繻葛之戰：鄭莊公擊敗周桓王的征討聯軍，鄭國兵士射傷天子肩膀——周天子被諸侯打傷，王室威信徹底崩潰，禮壞樂崩加速', textEn: 'Battle of Ruige: Zheng forces wound Zhou Tianzi\'s shoulder — Zhou royal prestige collapses entirely' },
  { year: -685,  text: '齊桓公即位，任管仲為相；管仲推行「相地而衰征」（按土地肥瘦收稅）、四民分業、尊王攘夷，齊國迅速富強', textEn: 'Duke Huan of Qi enthrones; appoints Guan Zhong as chancellor — land-tax reform and trade policies make Qi powerful' },
  { year: -684,  text: '長勺之戰：齊桓公攻魯，魯將曹劌以「一鼓作氣，再而衰，三而竭」戰術以少勝多——以弱勝強的著名範例，曹劌論戰流傳千古', textEn: 'Battle of Changshao: Cao Gui defeats Qi using "one beat, second weakens, third exhausts" — classic underdog victory' },
  { year: -678,  text: '葵丘之盟：齊桓公召集諸侯會盟，周天子賜胙肉；桓公成春秋第一霸，管仲所建立的「霸主秩序」取代天子號令成為新國際規範', textEn: 'Kuiqiu Covenant: Duke Huan of Qi becomes first hegemon of Spring and Autumn era' },
  { year: -655,  text: '假道伐虢：晉獻公借道虞國攻虢，宮之奇以「唇亡齒寒」力諫，虞君不聽；晉先滅虢，回師時順手滅虞——成語「假道伐虢」「唇亡齒寒」出此', textEn: 'Jin feigns passage through Yu to attack Guo; destroys both — "lips and teeth" proverb origin' },
  { year: -638,  text: '泓水之戰：宋襄公堅持「不鼓不成列」仁義而戰，被楚軍大敗；「宋襄之仁」成為迂腐的代名詞，春秋務實霸道取代周禮仁義', textEn: 'Battle of Hong River: Duke Xiang of Song loses by refusing to attack while Chu re-forms — "Song Xiang benevolence" becomes byword for folly' },
  { year: -636,  text: '晉公子重耳結束十九年流亡，回國即位為晉文公——歷經曹、衛、齊、楚、秦之旅，廣積人脈，翌年城濮大敗楚國稱霸中原', textEn: 'Chonger ends 19-year exile; becomes Duke Wen of Jin — defeats Chu at Chengpu, dominates Central Plains' },
  { year: -632,  text: '城濮之戰：晉文公「退避三舍」誘敵深入，大敗楚軍；踐土會盟稱霸，晉主導中原秩序長達百年', textEn: 'Battle of Chengpu: Jin retreats to lure Chu; routs Chu army; Duke Wen becomes hegemon' },
  { year: -627,  text: '殽之戰：晉軍於殽山全殲秦穆公遠征軍，秦東出受阻；秦轉而西向，稱霸西戎，埋下日後秦統六國的西方根基', textEn: 'Battle of Xiao: Jin annihilates Qin\'s expeditionary force; Qin turns westward to dominate Rong tribes' },
  { year: -594,  text: '魯國初稅畝：按實際耕地面積徵稅——中國最早記載的土地稅制改革，「井田制」瓦解的里程碑，私田合法化', textEn: 'Lu introduces land-area tax — China\'s earliest land tax reform; milestone in collapse of the well-field system' },
  { year: -597,  text: '邲之戰：楚莊王大敗晉師；戰前楚莊王「問鼎輕重」，直接挑戰周室，「問鼎中原」典故出此；楚稱霸中原，南北格局改變', textEn: 'Battle of Bi: Chu defeats Jin; King Zhuang "questions the cauldrons" — challenges Zhou supremacy; Chu becomes hegemon' },
  { year: -546,  text: '弭兵之盟：宋大夫向戌主持，晉楚各率 12 諸侯會盟；晉楚平分霸權，各國承認雙方盟主地位——春秋最大規模的國際和平協議', textEn: 'Covenant of Mibo: Jin and Chu divide hegemony among 24 states — Spring and Autumn\'s largest peace agreement' },
  { year: -544,  text: '孫武（孫子）約生於此前後，後赴吳國為將，著《孫子兵法》十三篇——人類歷史上影響最深遠的軍事著作，至今仍是各國軍校必讀', textEn: 'Sun Tzu (Sun Wu) born; later serves Wu, authors The Art of War — most enduring military treatise in history' },
  { year: -551,  text: '孔子誕生（西元前 551 年，魯國陬邑）——儒家思想創始人，整理六經，弟子三千，對東亞文明影響延續兩千五百年', textEn: 'Confucius born in Lu — founder of Confucianism; compiled Six Classics; 3,000 disciples; 2,500 years of influence' },
  { year: -522,  text: '伍子胥（伍員）出奔吳國：楚平王殺其父兄，伍子胥歷盡艱辛逃至吳國，助吳王闔閭強軍；後率吳軍攻破楚都郢，掘楚平王墓鞭屍三百', textEn: 'Wu Zixu flees to Wu after Chu kills his family; later leads Wu army to sack Chu capital, desecrates king\'s tomb' },
  { year: -506,  text: '吳楚柏舉之戰：吳王闔閭率伍子胥、孫武五戰攻入楚都郢；楚國幾亡，伍子胥掘楚平王墓鞭屍——春秋最大規模的征服戰', textEn: 'Battle of Boju: Wu armies led by Wu Zixu and Sun Tzu sack Chu capital Ying — largest conquest of the era' },
  { year: -496,  text: '夫椒之戰：吳王夫差大敗越國，越王勾踐入吳為奴；勾踐「臥薪嚐膽」，忍辱二十年積蓄力量', textEn: 'Wu defeats Yue; King Goujian becomes a servant in Wu — "sleeping on firewood, tasting gall" for 20 years' },
  { year: -484,  text: '孔子自衛返魯，結束長達十四年的周遊列國；晚年致力整理《詩》《書》《禮》《易》《春秋》，確立儒家五經體系', textEn: 'Confucius returns from 14-year travels; compiles the Five Classics in his final years' },
  { year: -479,  text: '孔子去世（享年 73 歲）；其言論由弟子整理為《論語》，成為儒家最核心典籍', textEn: 'Confucius dies, age 73; disciples compile his sayings as the Analects' },
  { year: -473,  text: '越王勾踐滅吳，夫差自刎；范蠡料定勾踐可共患難不可共富貴，棄官泛舟五湖，後經商成「陶朱公」——中國最早的商業傳奇', textEn: 'King Goujian of Yue destroys Wu; Fan Li resigns, becomes legendary merchant Tao Zhugong' },

  // ── 戰國（-475 ~ -221）──────────────────────────────────────────────────
  { year: -453,  text: '韓魏趙三家聯手滅智伯，瓜分其領地；晉國大夫架空晉侯，三家分晉之局實際已定（正式獲周王承認在前 403 年）', textEn: 'Han, Wei, Zhao eliminate Zhi Bo and divide his lands — Three Families partition Jin de facto complete' },
  { year: -403,  text: '三家分晉：周威烈王正式承認韓魏趙為諸侯——舊封建秩序崩潰的象徵，戰國七雄格局確立', textEn: 'Three Families Partition Jin formally recognized by Zhou king — Warring States period officially begins' },
  { year: -391,  text: '田氏代齊：田和廢齊康公，取代延續六百年的姜姓齊國——春秋以來的舊貴族秩序徹底瓦解', textEn: 'Tian clan replaces Qi (Jiang) — 600-year old Jiang-Qi dynasty ended; old aristocratic order collapses' },
  { year: -370,  text: '孟子（孟軻）約生於此時：繼承孔子仁學，提出「性善論」「仁政王道」「民貴君輕」，後世尊為「亞聖」', textEn: 'Mencius born — advocates innate goodness, benevolent governance, "people above ruler"; honored as Second Sage' },
  { year: -369,  text: '莊子（莊周）約生於此時：道家集大成者，《莊子》以寓言哲思探討自由與生死，深刻影響中國文學、藝術與禪宗', textEn: 'Zhuangzi born — Daoist master; parables on freedom and death; profound influence on Chinese art and Chan Buddhism' },
  { year: -356,  text: '商鞅變法：秦孝公任用商鞅推行全面改革（廢井田、連坐制、軍功爵位制），秦國迅速強大，為統一奠基', textEn: 'Shang Yang\'s reforms in Qin: abolish well fields, collective punishment, merit-based rank — Qin becomes dominant' },
  { year: -354,  text: '桂陵之戰：孫臏以「圍魏救趙」之計，率齊軍截擊魏將龐涓回援之師——間接路線戰略的經典範例，孫臏兵法雛形', textEn: 'Battle of Guiling: Sun Bin\'s "besiege Wei to rescue Zhao" — classic indirect strategy' },
  { year: -341,  text: '馬陵之戰：孫臏減灶誘敵，龐涓中伏身死，十萬魏軍覆沒；魏國稱霸中原的局面終結，東方格局重洗', textEn: 'Battle of Maling: Sun Bin\'s decreasing campfires ruse; Pang Juan killed; Wei\'s hegemony ends' },
  { year: -338,  text: '商鞅被秦惠文王以謀反罪逮捕，五牛分屍（車裂）；但商鞅之法未廢，秦國繼續依法強盛——制度比人更長久', textEn: 'Shang Yang executed by chariot-pulling; but his laws survive — institutions outlast individuals' },
  { year: -307,  text: '趙武靈王「胡服騎射」：廢棄車戰，引入北方騎兵戰術與服飾——戰國時代最成功的軍事改革，趙國一躍為強國', textEn: 'King Wuling of Zhao introduces "barbarian dress and mounted archery" — most successful Warring States military reform' },
  { year: -299,  text: '楚懷王輕信秦使張儀，入武關後遭秦昭王拘押；三年後客死秦國，不得歸葬；屈原因諫阻被流放，作《離騷》', textEn: 'King Huai of Chu lured to Qin, imprisoned; dies in captivity; poet Qu Yuan exiled, writes Li Sao' },
  { year: -286,  text: '宋康王 (「東方桀」) 末年暴虐無道；齊、魏、楚三國聯手瓜分宋國，宋存續約 760 年的社稷終結', textEn: 'Qi, Wei, Chu partition Song — 760-year-old Song State ends' },
  { year: -284,  text: '燕昭王任樂毅率五國聯軍伐齊，連下七十餘城，齊幾亡國；後田單以「火牛陣」復國——形勢逆轉的軍事奇蹟', textEn: 'Yue Yi leads five-state coalition against Qi; captures 70+ cities; Tian Dan later recovers Qi with Fire Ox Formation' },
  { year: -278,  text: '秦將白起率軍攻破楚都郢城；楚頃襄王東逃遷都；詩人屈原在汨羅江投水殉國——《離騷》《九歌》傳世，端午節由此而來', textEn: 'Qin general Bai Qi captures Chu capital Ying; poet Qu Yuan drowns in Miluo River — Dragon Boat Festival origin' },
  { year: -279,  text: '澠池之會：趙惠文王與秦昭王對峙，藺相如憑口才力保趙王尊嚴；廉頗「負荊請罪」，將相和，二人並稱廉藺', textEn: 'Mianchi Conference: Lin Xiangru defends King Huiwen\'s dignity against Qin; general Lian Po makes amends — "Lian and Lin" symbol of loyalty' },
  { year: -260,  text: '長平之戰：秦將白起坑殺趙軍降卒四十餘萬，趙國元氣大傷——中國古代規模最大的殲滅戰，六國再無力單獨抗秦', textEn: 'Battle of Changping: Bai Qi buries 400,000+ Zhao prisoners alive — largest annihilation battle in Chinese history' },
  { year: -256,  text: '秦昭王滅東周，赧王死，延續八百年的周朝徹底終結；此後天下僅剩秦與六國，統一之勢不可阻擋', textEn: 'Qin extinguishes Eastern Zhou; King Nan dies — 800-year Zhou dynasty ends; Qin unification inevitable' },
  { year: -239,  text: '呂不韋主持門客編寫《呂氏春秋》，匯集儒道名法各家精華——先秦思想的百科全書式總結，宣告諸子百家時代接近尾聲', textEn: 'Lü Buwei compiles Lüshi Chunqiu — encyclopedic synthesis of pre-Qin thought; Hundred Schools era draws to close' },

  // ── 秦漢 ────────────────────────────────────────────────────────────────────
  { year: -221,  text: '秦始皇統一六國，廢分封行郡縣；統一文字（小篆）、貨幣、度量衡，建立中央集權帝國制度', textEn: 'Qin Shi Huang unifies six states; establishes commandery-county system; standardizes script, currency, weights' },
  { year: -213,  text: '焚書坑儒：秦始皇焚燒諸子百家書籍，坑殺方士儒生——先秦學術文化遭受重大破壞', textEn: 'Burning of books and burying of scholars — major destruction of pre-Qin literature and thought' },
  { year: -209,  text: '陳勝吳廣起義，秦末農民戰爭爆發', textEn: 'Chen Sheng and Wu Guang Rebellion; Qin peasant wars erupt' },
  { year: -202,  text: '劉邦建立西漢，楚漢相爭結束', textEn: 'Liu Bang founds Western Han; Chu-Han contention ends' },
  { year: -138,  text: '張騫第一次出使西域，絲綢之路開通', textEn: 'Zhang Qian\'s first mission to Western Regions; Silk Road opens' },
  { year: 8,     text: '王莽篡漢，新朝建立', textEn: 'Wang Mang usurps Han throne; Xin Dynasty founded' },
  { year: 25,    text: '劉秀中興，東漢建立', textEn: 'Liu Xiu restores Han; Eastern Han founded' },
  { year: 105,   text: '蔡倫改進造紙術', textEn: 'Cai Lun improves papermaking technique' },
  { year: 184,   text: '黃巾之亂爆發', textEn: 'Yellow Turban Rebellion erupts' },

  // ── 三國 ────────────────────────────────────────────────────────────────────
  { year: 200,   text: '官渡之戰，曹操大敗袁紹', textEn: 'Battle of Guandu: Cao Cao decisively defeats Yuan Shao' },
  { year: 208,   text: '赤壁之戰，曹操敗於孫劉聯軍', textEn: 'Battle of Red Cliffs: Cao Cao defeated by Sun-Liu alliance' },
  { year: 220,   text: '曹丕稱帝，東漢亡，三國時代開始', textEn: 'Cao Pi proclaims Wei emperor; Eastern Han ends; Three Kingdoms era begins' },

  // ── 兩晉 ────────────────────────────────────────────────────────────────────
  { year: 280,   text: '西晉統一三國', textEn: 'Western Jin reunifies the Three Kingdoms' },
  { year: 304,   text: '五胡亂華，十六國時代開始', textEn: 'Five Barbarians in turmoil; Sixteen Kingdoms era begins' },
  { year: 316,   text: '匈奴攻陷洛陽，西晉亡', textEn: 'Xiongnu capture Luoyang; Western Jin falls' },
  { year: 383,   text: '淝水之戰，東晉大敗前秦，力保江南', textEn: 'Battle of Fei River: Eastern Jin defeats Former Qin; south of China preserved' },

  // ── 燕鄭衛魯吳越蔡陳韓趙魏 ───────────────────────────────────────────────────
  { year: -806,  text: '鄭桓公受封，建立鄭國', textEn: 'Duke Huan of Zheng enfeoffed; Zheng State founded' },
  { year: -771,  text: '鄭桓公殉難於犬戎之亂', textEn: 'Duke Huan of Zheng killed in Dog Rong invasion' },
  { year: -707,  text: '陳完（田完）之先祖陳厲公在位，後陳完奔齊，成田氏代齊之祖', textEn: 'Duke Li of Chen reigns; his descendant Chen Wan later flees to Qi, founding the Tian clan' },
  { year: -672,  text: '陳完奔齊，後代成為齊國田氏，並最終取代姜齊', textEn: 'Chen Wan flees to Qi; descendants become the Tian clan, eventually replacing Jiang-Qi' },
  { year: -664,  text: '齊桓公出兵救燕，擊退山戎，燕莊公感恩相送', textEn: 'Duke Huan of Qi rescues Yan from Shan Rong invasion' },
  { year: -660,  text: '衛懿公好鶴亡國：北狄攻衛，衛懿公戰死，衛幾亡', textEn: 'Duke Yi of Wei perishes defending against northern Di — Wei nearly destroyed' },
  { year: -597,  text: '趙氏孤兒：屠岸賈滅趙氏，程嬰保存趙武，韓厥協助', textEn: 'Orphan of the Zhao Clan: Tu\'an Jia destroys the Zhao; Cheng Ying rescues Zhao Wu with Han Jue\'s help' },
  { year: -547,  text: '申不害出生（約），後為韓昭侯推行法術改革', textEn: 'Shen Buhai born (approx.); later implements Legalist reforms for Han' },
  { year: -482,  text: '黃池之會：吳王夫差與晉定公爭霸，吳國鼎盛', textEn: 'Huangchi Conference: King Fuchai of Wu at height of power' },
  { year: -478,  text: '楚國滅陳，陳國終結', textEn: 'Chu destroys Chen State' },
  { year: -475,  text: '越王勾踐滅吳，吳王夫差自殺', textEn: 'King Goujian of Yue destroys Wu; King Fuchai commits suicide' },
  { year: -447,  text: '楚國滅蔡，蔡國終結', textEn: 'Chu destroys Cai State' },
  { year: -375,  text: '韓國滅鄭，鄭國終結', textEn: 'Han destroys Zheng State' },
  { year: -351,  text: '申不害為韓昭侯推行術治改革，韓國暫時強盛', textEn: 'Shen Buhai\'s reforms temporarily strengthen Han' },
  { year: -306,  text: '楚國滅越，越王無彊戰死，越國瓦解', textEn: 'Chu destroys Yue; Yue\'s last king killed in battle' },
  { year: -284,  text: '燕昭王遣樂毅伐齊，連下七十餘城', textEn: 'King Zhao of Yan sends Yue Yi against Qi; captures 70+ cities' },
  { year: -279,  text: '田單火牛陣復國，齊國收復失地，燕昭王剛逝', textEn: 'Tian Dan\'s Fire Ox Formation recovers Qi; King Zhao of Yan just died' },
  { year: -257,  text: '信陵君魏無忌竊符救趙，邯鄲解圍', textEn: 'Lord Xinling of Wei steals the military tally to rescue Zhao; siege of Handan lifted' },
  { year: -249,  text: '楚國滅魯，魯頃公被廢，魯國終結', textEn: 'Chu destroys Lu; last Zhou-era state ends' },
  { year: -230,  text: '秦滅韓，韓王安被俘', textEn: 'Qin destroys Han; King An captured' },
  { year: -228,  text: '秦滅趙，趙幽繆王被俘，公子嘉另立代國', textEn: 'Qin destroys Zhao; King Youmiu captured; Prince Jia establishes Dai State' },
  { year: -227,  text: '荊軻刺秦王：燕太子丹派荊軻入秦行刺，功敗垂成', textEn: 'Jing Ke attempts to assassinate King of Qin on behalf of Crown Prince Dan of Yan; fails' },
  { year: -225,  text: '秦滅魏，魏王假被俘', textEn: 'Qin destroys Wei; King Jia captured' },
  { year: -222,  text: '秦滅燕，燕王喜被俘', textEn: 'Qin destroys Yan; King Xi captured' },
  { year: -209,  text: '衛君角被秦二世廢為庶人，衛國正式終結，是最後一個被廢的周朝封國', textEn: 'Wei Junhao demoted to commoner by Qin Ershi — Wei State ends, last Zhou feudal state abolished' },
];
